### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 10bad1e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 10bad1e with merge 10bad1e...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 97b674d has been approved by `japaric`

**Comment by homunkulus** [comment]
:zap: Test exempted: merge already tested by Travis CI.

**Pull request merged**
