### PR TITLE
export_name -> no_mangle

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 189d1aa has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 189d1aa with merge 189d1aa...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/discovery/builds/176585434)
Approved by: japaric
Pushing 189d1aaaba437d301b1b1c32b315d9c52714983b to master...

**Pull request merged**
