### PR TITLE
note that older revisions need different openocd arguments

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e4bbab6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e4bbab6 with merge 28b90e2...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/discovery/builds/176588574)
Approved by: japaric
Pushing 28b90e2132876e0cc35cb35d33fd792e38ac1e64 to master...

**Pull request merged**
