### PR TITLE
fix(hello world): Changed 05-hello-world to 06-hello-world

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
There was a tiny typo with file names.

### CODE REVIEW

**Comment by japaric** [comment]
Thank you!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6f6e79e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6f6e79e with merge 187a4c7...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/discovery/builds/186104844)
Approved by: japaric
Pushing 187a4c717020c834bf7039d76c97fdf1f541888c to master...

**Pull request merged**
