### PR TITLE
02-requirements: add links to suppliers

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit dd2d3c7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit dd2d3c7 with merge dd2d3c7...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/discovery/builds/179131144)
Approved by: japaric
Pushing dd2d3c71002a3f74e16f730bd51a3d0fa97a31c5 to master...

**Pull request merged**
