### PR TITLE
fix CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 74d6afa has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 74d6afa with merge 74d6afa...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/discovery/builds/232660160?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 74d6afa96923cb35798c03bcbd2b4dd6ac7bf86a to master...

**Pull request merged**
