### PR TITLE
tweak CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ff55630 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ff55630 with merge ff55630...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/discovery/builds/185786429)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 494736b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 494736b with merge 494736b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/discovery/builds/185802034)
Approved by: japaric
Pushing 494736b2fb2597843b25043078a8fa21868219f0 to master...

**Pull request merged**
