### PR TITLE
add note about SB10

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ed008a2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ed008a2 with merge cba9794...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/discovery/builds/176587401)
Approved by: japaric
Pushing cba97946fb0fdcd1bc73545a8e577e04db37647c to master...

**Pull request merged**
