### PR TITLE
Updates code to match docs.

### PR DESCRIPTION
**Pull request by cldershem**
Code didn't match docs. `FACTOR` changed to `SENSITIVITY`. Also a small typo fix.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @cldershem.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c025218 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c025218b8c72e5a3ffff9e8a1f3b78b1d1d47f3c with merge 06a73b20e308b0700f255feb8f6ff40c9baf81ff...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/discovery/builds/289167054?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 06a73b20e308b0700f255feb8f6ff40c9baf81ff to master...

**Pull request merged**
