### PR TITLE
homu uses branch pushes no "pull requests" for its tests

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9babb22 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9babb22 with merge 9babb22...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 55e5671 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 55e5671 with merge 55e5671...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/discovery/builds/176593501)
Approved by: japaric
Pushing 55e5671105f18bfa12cdfbf35748a98270eae8f6 to master...

**Pull request merged**
